import { ROLES, effectRemaining } from './domain.js';
import { ABILITIES, CONDITIONS, signed, abilityBonus, saveBonus, defaultCombat, newAttack, parseDice, damageOptions } from './combat.js';
import { esc, button, sectionHead, empty } from './ui.js';

const rollButton=(label,p,kind,key='',manual=false,part='')=>{
  const attrs=`data-id="${p.id}" data-kind="${kind}" data-key="${esc(key)}" data-part="${esc(part)}"`;
  return `<span class="roll-control"><button type="button" class="secondary" data-action="${manual?'combat-roll':'quick-combat-roll'}" ${attrs}>${label}</button>${manual?'':`<button type="button" class="secondary roll-settings" data-action="combat-roll" ${attrs} aria-label="Настроить бросок: ${esc(label.replace(/<[^>]*>/g,''))}" title="Свои кости, преимущество, помеха или критический урон">⋯</button>`}</span>`;
};
function actionRolls(p,a) {
  const options=damageOptions(a),base=options.find(o=>!o.extra);
  return `<div class="actions">${a.bonus!==null?rollButton(`Попадание ${signed(a.bonus)}`,p,'attack',a.id):''}${base?rollButton(`Урон ${esc(base.formula)}`,p,'damage',a.id):a.bonus!==null||/damage/i.test(a.notes)?rollButton('Урон…',p,'damage',a.id,true):''}</div>${base?.note?`<p class="muted tiny">${esc(base.note)}</p>`:''}${options.map((o,i)=>o.extra?`<div class="conditional-damage">${rollButton(`${esc(o.label)} ${esc(o.formula)}`,p,'damage',a.id,true,String(i))}<p class="muted tiny">Только при выполнении условия: ${esc(o.note)}</p></div>`:'').join('')}`;
}
function recentRoll(b) {
  const r=b.rolls.at(-1);if(!r)return '';
  return `<div class="quick-roll-result" data-roll="${r.id}" aria-live="polite"><strong>${esc(r.actor)} · ${esc(r.label)}</strong><b>${r.total}</b><small>${esc(r.detail)}</small>${r.kind==='damage'?button('apply-roll-damage','Нанести урон','secondary',r.id):''}</div>`;
}
function effects(p,b) {
  return `<div class="effect-tags">${p.effects.map(e=>{
    const left=effectRemaining(e,b.round);
    return `<div class="effect-badge ${left===0?'effect-due':''}"><button class="effect-chip ${left===0?'expired':''}" data-action="remove-effect" data-id="${p.id}" data-effect="${e.id}" title="Снять: ${esc(e.name)}">${esc(e.name)} <small>${left===null?'∞':left===0?'проверьте срок':left+' раунд.'}</small> ×</button>${e.source?`<small>Источник: ${esc(e.source)}</small>`:''}${e.reminder?`<small>${esc(e.reminder)}</small>`:''}${CONDITIONS[e.name]?`<small class="muted">${esc(CONDITIONS[e.name])}</small>`:''}</div>`;
  }).join('')}</div>${p.conditions?`<p class="condition-note">${esc(p.conditions)}</p>`:''}${p.concentrationChecks.length?`<div class="concentration-warning"><strong>Концентрация: ТЕЛ СЛ ${p.concentrationChecks.join(', ')}</strong><span>Отдельная проверка за каждый удар.</span>${button('concentration-checked','Проверки пройдены','secondary',p.id)}${button('toggle-concentration','Потеряна','quiet',p.id)}</div>`:''}`;
}
function inspector(p,b) {
  if(!p)return `<aside class="panel combat-inspector">${empty('Действия врага','Выберите участника в очереди.')}</aside>`;
  if(p.role==='hero')return `<aside class="panel combat-inspector" data-inspected="${p.id}"><p class="eyebrow">ИГРОК</p><h2>${esc(p.name)}</h2><p>Состояния, источники эффектов и концентрация видны в очереди.</p><div class="actions">${button('add-effect','+ Состояние','primary',p.id)}${button('edit-combatant','Править игрока','secondary',p.id)}</div><p class="muted tiny">Выберите имя врага, чтобы открыть его атаки и спасброски. Карточка остаётся выбранной до перехода хода.</p></aside>`;
  const profile=p.combat;
  return `<aside class="panel combat-inspector" data-inspected="${p.id}"><p class="eyebrow">ПОД РУКОЙ</p><h2>${esc(p.name)}</h2><p class="muted">КД ${p.ac}${p.speed?' · '+esc(p.speed):''}</p><div class="actions">${button('edit-combat-profile','Править боевую карточку','quiet',p.id)}${button('combat-to-template','Сохранить как шаблон','quiet',p.id)}</div>
  ${recentRoll(b)}<div class="initiative-roll">${rollButton(`Инициатива ${signed(p.initiativeBonus)}`,p,'initiative')}</div><p class="muted tiny">Бросок — одним нажатием. ⋯ — свои кости и настройки.</p><h3>Спасброски</h3><div class="save-grid">${Object.entries(ABILITIES).map(([key,label])=>rollButton(`${label} <b>${signed(saveBonus(profile.abilities[key]))}</b>`,p,'save',key,saveBonus(profile.abilities[key])===null)).join('')}</div>
  <details><summary>Характеристики и навыки</summary><div class="save-grid">${Object.entries(ABILITIES).map(([key,label])=>rollButton(`${label} ${profile.abilities[key].score??'—'} (${signed(abilityBonus(profile.abilities[key].score))})`,p,'ability',key,profile.abilities[key].score===null)).join('')}</div><p class="preline muted tiny">${esc(profile.skills||'Навыки не записаны.')}</p></details>
  ${profile.defenses?`<div class="defense-note preline">${esc(profile.defenses)}</div>`:''}<h3>Действия</h3>
  ${profile.actions.map(a=>`<section class="enemy-action"><h4>${esc(a.name)}</h4><p class="muted tiny">${esc(a.range)}${a.saveDc!==null?` · ${ABILITIES[a.saveAbility]} СЛ <strong>${a.saveDc}</strong>`:''}</p>${actionRolls(p,a)}${a.notes?`<details><summary>Описание и условия</summary><p class="preline">${esc(a.notes)}</p></details>`:''}</section>`).join('')||'<p class="muted">Добавьте атаки и способности в боевую карточку или шаблон врага.</p>'}
  ${p.notes?`<details class="combat-notes"><summary>Полный текст и заметки</summary><div class="preline">${esc(p.notes)}</div></details>`:''}<details><summary>Свои формулы</summary><div class="actions">${rollButton('Попадание…',p,'attack','',true)}${rollButton('Урон…',p,'damage','',true)}</div></details></aside>`;
}
export function combatPage(c,selectedId) {
  const b=c.battle,selected=b.combatants.find(p=>p.id===(selectedId||b.activeId))||b.combatants.find(p=>p.role==='enemy')||b.combatants[0];
  const templates=c.entries.filter(e=>e.type==='monster');
  return `${sectionHead('ПУЛЬТ ВЕДУЩЕГО','Бой','HP врагов, состояния группы и действия существ.',button('combat-library','+ Из бестиария','primary')+button('new-player','+ Игрок','secondary')+button('new-combatant','+ Участник','secondary')+button('new-monster-template','+ Свой монстр','secondary'))}
  <div class="combat-toolbar"><div><span class="eyebrow">${b.started?'РАУНД':'ПОДГОТОВКА'}</span><strong>${b.started?b.round:'Соберите встречу'}</strong></div><div class="actions">${b.started?button('previous-turn','← Назад','secondary')+button('next-turn','Следующий ход →','primary'):button('start-battle','Начать бой','primary')}${button('undo-battle','Отменить','secondary')}${button('clear-battle','Завершить','quiet')}</div></div>
  <div class="battle-tools"><div class="actions">${button('roll-enemies','d20 Инициатива противникам','secondary')}${button('sort-battle','Сортировать','secondary')}${button('save-encounter','Сохранить заготовку','secondary')}</div><span class="muted tiny">← / → — ход · Срок эффекта: начало раунда, снятие вручную</span></div>
  ${b.combatants.some(p=>p.role==='hero')?`<section class="party-overview"><h3>Состояния группы</h3><div class="party-grid">${b.combatants.filter(p=>p.role==='hero').map(p=>`<article class="party-card"><div class="party-title">${button('add-effect',esc(p.name)+' +','quiet',p.id)}${p.concentration?'<span class="party-concentration">◈ Концентрация</span>':''}</div>${p.effects.map(e=>`<p class="${effectRemaining(e,b.round)===0?'party-due':''}"><strong>${esc(e.name)}</strong>${effectRemaining(e,b.round)===0?' · проверьте срок':''}${e.source?' · '+esc(e.source):''}${e.reminder?`<small>${esc(e.reminder)}</small>`:''}</p>`).join('')}${p.conditions?`<p>${esc(p.conditions)}</p>`:''}${!p.effects.length&&!p.conditions?'<span class="muted tiny">Нет записанных состояний</span>':''}${p.concentrationChecks.length?`<p class="party-due">Концентрация: ТЕЛ СЛ ${p.concentrationChecks.join(', ')}</p>`:''}</article>`).join('')}</div></section>`:''}
  <div class="combat-workspace"><div class="combat-roster"><div class="combatants">${b.combatants.map((p,i)=>`<article class="combatant ${b.activeId===p.id?'current':''} ${selected?.id===p.id?'inspected':''}" data-combatant="${p.id}"><div class="initiative"><span>Иниц.</span><strong>${p.initiative}</strong>${button('roll-one','d20','roll-button',p.id)}</div><div class="combatant-name"><span class="tiny ${b.activeId===p.id?'turn-label':'muted'}">${b.activeId===p.id?'СЕЙЧАС ХОДИТ · ':''}${ROLES[p.role]}</span><h2><button class="combat-name-button" data-action="inspect-combatant" data-id="${p.id}">${esc(p.name)}</button></h2><p class="muted tiny">${p.trackHp?`КД ${p.ac} · `:''}Инициатива ${signed(p.initiativeBonus)}</p></div>${p.trackHp?`<div class="health"><span><strong>${p.hp}</strong> / ${p.maxHp} HP${p.tempHp?` <small>+${p.tempHp} врем.</small>`:''}</span><div class="health-track"><i style="width:${Math.round(p.hp/p.maxHp*100)}%"></i></div></div>`:'<span class="muted tiny">HP ведёт игрок</span>'}
  ${p.effects.length||p.conditions||p.concentrationChecks.length?`<div class="combat-status">${effects(p,b)}</div>`:''}<div class="actions combat-actions">${p.trackHp?`<input type="number" min="0" max="100000" step="1" data-hp-input="${p.id}" aria-label="Урон или лечение: ${esc(p.name)}" placeholder="Число"><select data-damage-scale="${p.id}" aria-label="Множитель урона: ${esc(p.name)}"><option value="1">×1</option><option value="0.5">½</option><option value="2">×2</option></select>${button('damage','− Урон','damage',p.id)}${button('heal','+ HP','healing',p.id)}`:''}${button('add-effect','+ Состояние','secondary',p.id)}<button class="${p.concentration?'concentrating':'quiet'}" data-action="toggle-concentration" data-id="${p.id}" aria-pressed="${p.concentration}">◈ Концентрация</button>${button('inspect-combatant','Броски','secondary',p.id)}${button('edit-combatant','Править','quiet',p.id)}<span class="turn-order"><button class="icon-button" data-action="move-up" data-id="${p.id}" aria-label="Поднять ${esc(p.name)}" ${i===0?'disabled':''}>↑</button><button class="icon-button" data-action="move-down" data-id="${p.id}" aria-label="Опустить ${esc(p.name)}" ${i===b.combatants.length-1?'disabled':''}>↓</button></span></div></article>`).join('')||empty('Добавьте участников','Создайте своего монстра или выберите готового из SRD.',button('combat-library','Выбрать из SRD','primary'))}</div>
  ${b.rolls.length?`<section class="panel combat-roll-log" aria-live="polite"><h3>Последние броски</h3>${b.rolls.slice(-8).reverse().map(r=>`<div class="roll-result"><div><strong>${esc(r.actor)} · ${esc(r.label)}</strong><small>${esc(r.detail)}</small></div><b>${r.total}</b>${r.kind==='damage'?button('apply-roll-damage','Нанести','secondary',r.id):''}</div>`).join('')}</section>`:''}</div>${inspector(selected,b)}</div>
  <details class="encounter-library" open><summary>Мои шаблоны врагов (${templates.length})</summary><div class="actions">${button('new-monster-template','+ Новый шаблон','primary')}</div><div class="encounter-grid">${templates.map(e=>`<article class="panel monster-template" data-template="${e.id}"><h3>${esc(e.name)}</h3><p class="muted tiny">КД ${e.stats.ac} · ${e.stats.maxHp} HP · ${e.stats.combat.actions.length} действий</p><div class="actions">${button('template-to-combat','В бой…','primary',e.id)}${button('edit-monster-template','Править','secondary',e.id)}${button('duplicate-monster-template','Копия','quiet',e.id)}${button('entry','Заметка','quiet',e.id)}</div></article>`).join('')||'<p class="muted">Сохраните характеристики и атаки собственного существа. Каждый участник боя получит свою копию.</p>'}</div></details>
  <details class="encounter-library" ${c.encounters.length?'open':''}><summary>Заготовки встреч (${c.encounters.length})</summary><div class="encounter-grid">${c.encounters.map(e=>`<article class="panel"><h3>${esc(e.name)}</h3><p class="muted tiny">${e.combatants.length} участников</p><div class="actions">${button('load-encounter','Загрузить','secondary',e.id)}${button('delete-encounter','Удалить','quiet',e.id)}</div></article>`).join('')}</div></details><div class="note-strip"><p>Музыка и звуки продолжают играть во время боя.</p>${button('go-sound','Звуковая панель','text-button')}${button('new-event','Записать событие','text-button')}</div>`;
}

export function actionFields(action=newAttack(),field,selectField) {
  const a=action,prefix=`action-${a.id}-`;
  return `<fieldset class="attack-editor" data-attack-editor="${a.id}"><legend>Атака / способность</legend>${field('Название',prefix+'name',a.name,{required:true})}<div class="form-grid">${field('Бонус атаки (пусто — нет броска)',prefix+'bonus',a.bonus??'',{type:'number',min:-100,max:100})}${field('Урон: 2d6 + 3',prefix+'damage',a.damage,{maxLength:100})}${field('Дальность / досягаемость',prefix+'range',a.range)}${field('СЛ спасброска (если есть)',prefix+'saveDc',a.saveDc??'',{type:'number',max:100})}${selectField('Спасбросок цели',prefix+'saveAbility',ABILITIES,a.saveAbility)}</div>${field('Тип урона, условия, частота и особенности',prefix+'notes',a.notes,{area:true,rows:3,maxLength:10000})}${button('remove-attack-field','Удалить действие','danger-text',a.id)}</fieldset>`;
}
export function profileFields(profile=defaultCombat(),field,selectField) {
  return `<details class="profile-abilities"><summary>Характеристики, спасброски, навыки и защита</summary><p class="muted tiny">Пусто — значение неизвестно. Если бонус спасброска не указан, используется модификатор характеристики.</p><div class="ability-editor">${Object.entries(ABILITIES).map(([key,label])=>`<div><strong>${label}</strong>${field('Значение',key+'Score',profile.abilities[key].score??'',{type:'number',min:1,max:30})}${field('Бонус спасброска',key+'Save',profile.abilities[key].save??'',{type:'number',min:-100,max:100})}</div>`).join('')}</div>${field('Навыки и бонусы','skills',profile.skills,{area:true,rows:2,maxLength:2000})}${field('Сопротивления, иммунитеты, уязвимости','defenses',profile.defenses,{area:true,rows:2,maxLength:4000})}</details><h3>Атаки и способности</h3><div id="attack-fields">${profile.actions.map(a=>actionFields(a,field,selectField)).join('')}</div>${button('add-attack-field','+ Добавить действие','secondary')}`;
}
export function readProfile(data,form) {
  const nullable=name=>data.get(name)===''?null:Number(data.get(name));
  const p=defaultCombat();
  for(const key of Object.keys(ABILITIES))p.abilities[key]={score:nullable(key+'Score'),save:nullable(key+'Save')};
  p.skills=data.get('skills');p.defenses=data.get('defenses');
  p.actions=[...form.querySelectorAll('[data-attack-editor]')].map(el=>{
    const id=el.dataset.attackEditor,k=`action-${id}-`,damage=data.get(k+'damage').trim();if(damage)parseDice(damage);
    return {id,name:data.get(k+'name').trim(),bonus:nullable(k+'bonus'),damage,range:data.get(k+'range'),saveDc:nullable(k+'saveDc'),saveAbility:data.get(k+'saveAbility'),notes:data.get(k+'notes')};
  });
  return p;
}
