import { esc, button, sectionHead } from './ui.js';
export const isDesktop=!!globalThis.dmw;
export let nativeInfo={root:'',warning:'',aiProgress:'',aiBusy:false,aiDir:''};
export async function refreshNativeInfo() {if(isDesktop)nativeInfo=await globalThis.dmw.info();return nativeInfo;}
export function desktopAI() {
  return `<section class="panel"><h3>Локальный ИИ</h3><p class="muted tiny">${esc(nativeInfo.aiProgress||'Помощник запускается вместе с приложением.')}</p><div class="actions">${button('native-ai-start','Запустить ИИ','secondary')}${button('native-ai-folder','Подключить установленный ИИ','quiet')}${button('native-ai-install','Скачать ИИ · около 4,8 ГБ','quiet')}</div><p class="tiny muted">Интернет нужен только для первой загрузки движка и модели. Встроенная загрузка пока доступна в Linux x64. На Windows/macOS используется установленный Ollama.</p></section>`;
}
export function desktopPage() {
  return `${sectionHead('ВАШИ ДАННЫЕ НА КОМПЬЮТЕРЕ','Хранилище и резервные копии','Заметки в Markdown, состояние кампаний и аудио сохраняются на диске.')}
  <section class="panel"><h2>Папка хранилища</h2><code class="vault-path">${esc(nativeInfo.root)}</code><p class="muted">Открой папку notes нужной кампании как хранилище Obsidian. После внешних изменений нажми «Обновить записи». Имена, перемещения, новый текст и новые .md-файлы будут прочитаны с диска.</p><div class="actions">${button('native-open','Открыть папку','primary')}${button('native-refresh','Обновить записи','secondary')}${button('native-library','Открыть другое хранилище','quiet')}</div>${nativeInfo.warning?`<p role="alert" class="memory-error">${esc(nativeInfo.warning)}</p>`:''}</section>
  <div class="overview-grid"><section class="panel"><h2>Полная резервная копия</h2><p>Все кампании, заметки, музыка, профиль стиля и Markdown-память — в одном файле. Восстановление создаёт новую папку.</p><div class="actions">${button('native-backup','Сохранить полную копию','primary')}${button('native-restore','Восстановить копию','secondary')}</div><p class="muted tiny">Раз в день при открытии хранилища создаётся копия в backups/. Хранятся последние 14 копий. Копию для защиты от поломки диска сохраняй отдельно. Модель ИИ в копию не входит.</p></section>
  <section class="panel"><h2>Перенос из веб-версии</h2><p>В прежней версии сохрани каждую кампанию в JSON, затем импортируй файлы здесь. Заметки, бой, переписка и аудио будут перенесены.</p><div class="actions">${button('import','Импорт кампании JSON','secondary')}${button('ai-import-profile','Импорт профиля стиля','quiet')}${button('native-memory-import','Импорт папки памяти','quiet')}</div><p class="muted tiny">После кампаний выбери прежнюю vault/memory/: её записи будут сопоставлены с импортированными кампаниями. Исходные данные остаются в браузере.</p></section></div>${desktopAI()}`;
}
