import { TYPES, HOOKS, ROLES } from './domain.js';
import { esc, icon, button, empty } from './ui.js';
import { noteFolder, noteLinks, markdown } from './markdown.js';

export function filterEntries(c,s) {
  return c.entries.filter(e => (!s.filter || e.type===s.filter) && (!s.pinnedOnly || e.pinned) && (!s.tagFilter || e.tags.includes(s.tagFilter)) && `${e.name} ${e.text} ${e.tags.join(' ')}`.toLocaleLowerCase('ru').includes(s.query.toLocaleLowerCase('ru'))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||(s.sort==='name'?a.name.localeCompare(b.name,'ru'):b.updatedAt.localeCompare(a.updatedAt)));
}
export function entriesList(c,s) {
  const entries=filterEntries(c,s),root={notes:[],children:new Map()};
  for(const e of entries) {
    let node=root;
    for(const part of noteFolder(e).split('/').filter(Boolean)){if(!node.children.has(part))node.children.set(part,{notes:[],children:new Map()});node=node.children.get(part);}
    node.notes.push(e);
  }
  function tree(node) {
    return [...node.children].sort(([a],[b])=>a.localeCompare(b,'ru')).map(([name,child])=>`<details class="note-folder" open><summary>${icon('folder')}<span>${esc(name)}</span></summary><div>${tree(child)}</div></details>`).join('')+node.notes.map(e=>`<button class="entry-card file-row ${s.selected===e.id?'active-entry':''}" data-action="entry" data-id="${e.id}" title="${esc(e.name)}">${icon(e.type==='monster'?'sword':'journal')}<span>${esc(e.name)}</span>${e.pinned?'<small>★</small>':''}</button>`).join('');
  }
  return entries.length?tree(root):'<p class="muted tiny tree-empty">Нет подходящих заметок.</p>';
}
function connections(c,e) {
  const outgoing=noteLinks(c,e);
  return c.entries.filter(x=>x.id!==e.id && (outgoing.includes(x.id)||noteLinks(c,x).includes(e.id)));
}
function graph(c,e) {
  const all=connections(c,e),nodes=all.slice(0,8);
  return `<div class="local-graph"><svg viewBox="0 0 240 190" role="img" aria-label="Связи заметки ${esc(e.name)}">${nodes.map((x,i)=>{const a=i/Math.max(1,nodes.length)*Math.PI*2-Math.PI/2,xp=120+82*Math.cos(a),yp=95+64*Math.sin(a);return `<line x1="120" y1="95" x2="${xp}" y2="${yp}"/><a href="#" data-action="entry" data-id="${x.id}" aria-label="Открыть ${esc(x.name)}"><circle cx="${xp}" cy="${yp}" r="5"/><text x="${xp}" y="${yp+17}" text-anchor="middle">${esc(x.name.slice(0,17))}</text></a>`;}).join('')}<circle class="graph-center" cx="120" cy="95" r="8"/><text x="120" y="118" text-anchor="middle">${esc(e.name.slice(0,19))}</text></svg><p class="tiny muted">${all.length} связей${all.length>8?' · показано 8':''}</p></div>`;
}
export function knowledgePage(c,s) {
  const e=c.entries.find(x=>x.id===s.selected),tags=[...new Set(c.entries.flatMap(x=>x.tags))].sort();
  const links=e?noteLinks(c,e):[],backlinks=e?c.entries.filter(x=>x.id!==e.id&&noteLinks(c,x).includes(e.id)):[];
  const text=s.draft?.text??e?.text??'';
  return `<section class="vault-workspace">
  <aside class="vault-explorer"><div class="vault-title"><span>${icon('book')} База знаний</span>${button('new-entry','+','icon-button')}</div><p class="vault-world">${esc(c.name)}</p><label class="search">${icon('search')}<input id="search" type="search" aria-label="Поиск в базе знаний" placeholder="Найти заметку…  Ctrl K" value="${esc(s.query)}"></label><details class="vault-filters"><summary>Фильтры и сортировка</summary><select id="type-filter" aria-label="Тип записи"><option value="">Все типы</option>${Object.entries(TYPES).map(([k,v])=>`<option value="${k}" ${s.filter===k?'selected':''}>${v}</option>`).join('')}</select><select id="tag-filter" aria-label="Тег"><option value="">Все теги</option>${tags.map(t=>`<option ${s.tagFilter===t?'selected':''} value="${esc(t)}">${esc(t)}</option>`).join('')}</select><select id="entry-sort" aria-label="Сортировка"><option value="recent">Недавно изменённые</option><option value="name" ${s.sort==='name'?'selected':''}>По имени</option></select><label class="checkbox"><input id="pinned-filter" type="checkbox" ${s.pinnedOnly?'checked':''}> Только закреплённые</label></details><div class="explorer-caption">ЗАМЕТКИ <span>${c.entries.length}</span></div><div id="entries" class="file-tree">${entriesList(c,s)}</div><div class="explorer-footer">${button('new-entry',icon('plus')+' Новая заметка','quiet')}<small>Папку можно задать в свойствах</small></div></aside>
  <section class="vault-document"><div class="note-tabs">${s.tabs.map(id=>c.entries.find(x=>x.id===id)).filter(Boolean).map(x=>`<button data-action="entry" data-id="${x.id}" class="note-tab ${x.id===s.selected?'active':''}">${icon('journal')}<span>${esc(x.name)}</span></button>`).join('')||'<span class="muted">Мир начинается с заметки</span>'}</div><div class="document-toolbar"><span class="note-breadcrumb">${e?esc(noteFolder(e)||'Хранилище')+' / '+esc(e.name):'База знаний'}</span><div class="actions">${e?button('note-mode',s.editing?'Читать':'Писать',s.editing?'primary':'quiet')+button('edit-entry','Свойства','quiet',e.id):''}</div></div><article class="entry-reader" id="entry-reader">${e?`<div class="document-meta"><span class="badge">${TYPES[e.type]}</span>${button('pin-entry',e.pinned?'★ Закреплено':'☆ Закрепить','quiet',e.id)}</div><h2 class="document-title">${esc(e.name)}</h2><div class="tags">${e.tags.map(t=>`<span>#${esc(t)}</span>`).join('')}</div>${s.editing?`<div class="markdown-hint"># Заголовок · **выделение** · [[Название заметки]]</div><textarea id="note-text" class="markdown-editor" maxlength="100000" aria-label="Текст заметки в Markdown" spellcheck="true" placeholder="Расскажи об этом месте, персонаже или событии…">${esc(text)}</textarea>`:`<div class="reader-prose markdown-body">${markdown(text||'*Здесь ещё нет текста. Нажмите «Писать».*',c.entries)}</div>`}`:empty('Собери свой мир','Создай первую заметку. Связывай персонажей, места и события через [[ссылки]].',button('new-entry','Создать заметку','primary'))}</article><footer class="document-status"><span id="note-save-status">${s.draft?'Есть несохранённый черновик':'Сохранено на устройстве'}</span><div class="actions">${e?button('note-export','↓ .md','quiet',e.id):''}${s.draft?button('note-discard','Сбросить черновик','quiet'):''}${e&&s.editing?button('note-save','Сохранить · Ctrl S','primary'):''}</div></footer></section>
  <aside class="vault-inspector">${e?`<div class="inspector-section"><h3>СВОЙСТВА</h3><dl><dt>Тип</dt><dd>${TYPES[e.type]}</dd><dt>Папка</dt><dd>${esc(noteFolder(e)||'Корень')}</dd>${e.type==='hook'?`<dt>Зацепка</dt><dd>${HOOKS[e.status]}</dd>`:''}</dl>${['npc','monster'].includes(e.type)?`<div class="note-stats"><span>КД <b>${e.stats.ac}</b></span><span>HP <b>${e.stats.maxHp}</b></span><span>Иниц. <b>${e.stats.initiativeBonus}</b></span></div><p class="tiny muted">${ROLES[e.stats.role]} · ${esc(e.stats.speed)}</p>${button('entry-to-combat',icon('sword')+' В бой','secondary',e.id)}`:''}</div><div class="inspector-section"><h3>КАРТА СВЯЗЕЙ</h3>${graph(c,e)}</div><div class="inspector-section"><h3>ИСХОДЯЩИЕ ССЫЛКИ <span>${links.length}</span></h3>${links.map(id=>button('entry',esc(c.entries.find(x=>x.id===id).name),'backlink-button',id)).join('')||'<p class="tiny muted">Напиши [[Название]] в тексте.</p>'}</div><div class="inspector-section"><h3>ОБРАТНЫЕ ССЫЛКИ <span>${backlinks.length}</span></h3>${backlinks.map(x=>button('entry',esc(x.name),'backlink-button',x.id)).join('')||'<p class="tiny muted">Пока никто не ссылается на эту заметку.</p>'}${c.sessions.filter(x=>x.links.includes(e.id)).map(x=>button('session','Сессия: '+esc(x.name),'backlink-button',x.id)).join('')}${c.events.filter(x=>x.links.includes(e.id)).map(x=>button('jump-event','Событие: '+esc(x.text.slice(0,70)),'backlink-button',x.id)).join('')}</div>`:'<div class="inspector-section"><h3>СВЯЗИ ВАШЕГО МИРА</h3><p class="muted">Свойства и упоминания открытой заметки появятся здесь.</p></div>'}</aside></section>`;
}
