import { TYPES, HOOKS, ROLES, SOUND_KINDS, effectRemaining } from './domain.js';
import { esc, icon, button, sectionHead, empty } from './ui.js';

export function filterEntries(c, state) {
  const entries = c.entries.filter(e => (!state.filter || e.type === state.filter) && (!state.pinnedOnly || e.pinned) && (!state.tagFilter || e.tags.includes(state.tagFilter)) && `${e.name} ${e.text} ${e.tags.join(' ')}`.toLocaleLowerCase('ru').includes(state.query.toLocaleLowerCase('ru')));
  return entries.sort((a, b) => Number(b.pinned) - Number(a.pinned) || (state.sort === 'name' ? a.name.localeCompare(b.name, 'ru') : b.updatedAt.localeCompare(a.updatedAt)));
}
export function entriesList(c, state) {
  return filterEntries(c, state).map(e => `<button class="entry-card ${state.selected === e.id ? 'active-entry' : ''}" data-action="entry" data-id="${e.id}"><span class="type-icon type-${e.type}">${icon(e.type === 'location' ? 'folder' : e.type === 'monster' ? 'sword' : 'book')}</span><span class="badge">${e.pinned ? '★ ' : ''}${TYPES[e.type]}</span><h2>${esc(e.name)}</h2><p class="muted clamp">${esc(e.text || 'История этой записи ещё не написана.')}</p><div class="tags">${e.tags.map(t => `<span>#${esc(t)}</span>`).join('')}${e.type === 'hook' ? `<span>${HOOKS[e.status]}</span>` : ''}</div></button>`).join('') || empty('Записей не найдено', 'Измените фильтры или создайте новую запись.', button('new-entry', 'Добавить запись', 'primary'));
}
export function knowledgePage(c, state) {
  const e = c.entries.find(e => e.id === state.selected), tags = [...new Set(c.entries.flatMap(e => e.tags))].sort((a,b) => a.localeCompare(b,'ru'));
  return `${sectionHead('МИР, В КОТОРОМ ВСЁ СВЯЗАНО', 'База знаний', 'Читайте материалы, связывайте факты и готовьте встречи.', button('new-entry', icon('plus') + ' Добавить запись', 'primary'))}
  <div class="knowledge-filters"><label class="search">${icon('search')}<input id="search" type="search" placeholder="Название, текст, тег…" aria-label="Поиск в базе знаний" value="${esc(state.query)}"></label><select id="type-filter" aria-label="Тип записи"><option value="">Все типы</option>${Object.entries(TYPES).map(([key,label]) => `<option value="${key}" ${state.filter === key ? 'selected' : ''}>${label}</option>`).join('')}</select><select id="tag-filter" aria-label="Тег"><option value="">Все теги</option>${tags.map(t => `<option value="${esc(t)}" ${state.tagFilter === t ? 'selected' : ''}>${esc(t)}</option>`).join('')}</select><select id="entry-sort" aria-label="Сортировка"><option value="recent">Недавно изменённые</option><option value="name" ${state.sort === 'name' ? 'selected' : ''}>По имени</option></select><label class="checkbox"><input type="checkbox" id="pinned-filter" ${state.pinnedOnly ? 'checked' : ''}>Закреплённые</label></div>
  <div class="knowledge-workspace"><div id="entries" class="entry-grid">${entriesList(c, state)}</div><section class="entry-reader panel" id="entry-reader">${e ? entryReader(c, e) : empty('Откройте запись', 'Материалы появятся здесь. На время игры редактор можно оставить закрытым.')}</section></div>`;
}
function entryReader(c, e) {
  const backlinks = [...c.entries.filter(x => x.links.includes(e.id)).map(x => button('entry', esc(x.name), 'backlink-button', x.id)), ...c.sessions.filter(s => s.links.includes(e.id)).map(s => button('session', 'Сессия: ' + esc(s.name), 'backlink-button', s.id)), ...c.events.filter(x => x.links.includes(e.id)).map(x => button('jump-event', esc('Событие: ' + x.text.slice(0, 100)), 'backlink-button', x.id))];
  const combat = ['npc', 'monster'].includes(e.type);
  return `<div class="reader-heading"><span class="badge">${TYPES[e.type]}</span><div class="actions">${button('pin-entry', e.pinned ? '★ Закреплено' : '☆ Закрепить', 'quiet', e.id)}${button('edit-entry', 'Редактировать', 'secondary', e.id)}</div></div><h2>${esc(e.name)}</h2><div class="tags">${e.tags.map(t => `<span>#${esc(t)}</span>`).join('')}</div>${combat ? `<div class="stat-block"><div><small>Класс доспеха</small><strong>${e.stats.ac}</strong></div><div><small>Хиты</small><strong>${e.stats.maxHp}</strong></div><div><small>Бонус инициативы</small><strong>${e.stats.initiativeBonus >= 0 ? '+' : ''}${e.stats.initiativeBonus}</strong></div><div><small>Скорость</small><strong>${esc(e.stats.speed)}</strong></div></div><div class="actions">${button('entry-to-combat', icon('sword') + ' Добавить в бой', 'primary', e.id)}<span class="muted tiny">${ROLES[e.stats.role]} · независимая копия</span></div>` : ''}<div class="reader-prose preline">${esc(e.text || 'Текст пока не добавлен.')}</div><h3>Связанные материалы</h3><div class="tags">${e.links.map(id => { const x = c.entries.find(x => x.id === id); return button('entry', esc(x.name), 'link-chip', id); }).join('') || '<p class="muted tiny">Добавьте связи в редакторе.</p>'}</div><div class="backlinks"><h3>Где упоминается</h3>${backlinks.join('') || '<p class="muted tiny">Другие записи пока не ссылаются на этот материал.</p>'}</div>`;
}
export function combatPage(c) {
  const b = c.battle;
  return `${sectionHead('ПУЛЬТ ВЕДУЩЕГО', 'Бой', 'Участники, эффекты и заготовки встреч — в одном месте.', button('combat-library', icon('book') + ' Бестиарий SRD', 'secondary') + button('new-combatant', icon('plus') + ' Участник', 'primary'))}
  <div class="combat-toolbar"><div><span class="eyebrow">${b.started ? 'РАУНД' : 'ПОДГОТОВКА'}</span><strong>${b.started ? b.round : 'Соберите встречу'}</strong></div><div class="actions">${b.started ? button('previous-turn','← Назад','secondary') + button('next-turn','Следующий ход ' + icon('arrow'),'primary') : button('start-battle','Начать бой','primary')}${button('undo-battle','Отменить','secondary')}${button('clear-battle','Завершить','quiet')}</div></div>
  <div class="battle-tools"><div class="actions">${button('roll-enemies',icon('dice') + ' Инициатива противникам','secondary')}${button('sort-battle','Сортировать','secondary')}${button('save-encounter','Сохранить заготовку','secondary')}</div><span class="muted tiny">← / → — ход · Эффекты считаются до начала указанного раунда</span></div>
  <div class="combatants">${b.combatants.map((p,i) => `<article class="combatant ${b.activeId === p.id ? 'current' : ''}" data-combatant="${p.id}"><div class="initiative"><span>Иниц.</span><strong>${p.initiative}</strong>${button('roll-one','d20','roll-button',p.id)}</div><div class="combatant-name"><span class="tiny ${b.activeId === p.id ? 'turn-label' : 'muted'}">${b.activeId === p.id ? 'СЕЙЧАС ХОДИТ · ' : ''}${ROLES[p.role]}</span><h2>${esc(p.name)}</h2><p class="muted tiny">КД ${p.ac} · Бонус инициативы ${p.initiativeBonus >= 0 ? '+' : ''}${p.initiativeBonus}${p.concentration ? ' · ◈ Концентрация' : ''}</p><div class="effect-tags">${p.effects.map(effect => { const left = effectRemaining(effect,b.round); return `<button class="effect-chip ${left === 0 ? 'expired' : ''}" data-action="remove-effect" data-id="${p.id}" data-effect="${effect.id}" title="Снять эффект">${esc(effect.name)} <small>${left === null ? '∞' : left === 0 ? 'истёк' : left + ' раунд.'}</small> ×</button>`; }).join('')}</div>${p.conditions ? `<p class="muted tiny">${esc(p.conditions)}</p>` : ''}</div><div class="health"><span><strong>${p.hp}</strong> / ${p.maxHp} HP${p.tempHp ? ` <small>+${p.tempHp} врем.</small>` : ''}</span><div class="health-track"><i style="width:${Math.round(p.hp/p.maxHp*100)}%"></i></div></div><div class="actions combat-actions"><input type="number" min="0" max="100000" step="1" data-hp-input="${p.id}" aria-label="Урон или лечение: ${esc(p.name)}" placeholder="Число"><select data-damage-scale="${p.id}" aria-label="Множитель урона: ${esc(p.name)}"><option value="1">×1</option><option value="0.5">½</option><option value="2">×2</option></select>${button('damage','− Урон','damage',p.id)}${button('heal','+ HP','healing',p.id)}${button('add-effect','Эффект','secondary',p.id)}${button('edit-combatant','Править','quiet',p.id)}<button class="icon-button" data-action="move-up" data-id="${p.id}" aria-label="Поднять ${esc(p.name)}" ${i===0?'disabled':''}>↑</button><button class="icon-button" data-action="move-down" data-id="${p.id}" aria-label="Опустить ${esc(p.name)}" ${i===b.combatants.length-1?'disabled':''}>↓</button></div>${p.notes ? `<details class="combat-notes"><summary>Действия и заметки</summary><div class="preline">${esc(p.notes)}</div></details>` : ''}</article>`).join('') || empty('Добавьте участников', 'Создайте их вручную или возьмите характеристики из базы знаний.', button('combat-library','Выбрать из SRD','primary'))}</div>
  <details class="encounter-library" ${c.encounters.length ? 'open' : ''}><summary>Заготовки встреч (${c.encounters.length})</summary><div class="encounter-grid">${c.encounters.map(e => `<article class="panel"><h3>${esc(e.name)}</h3><p class="muted tiny">${e.combatants.length} участников · ${esc(e.combatants.map(p=>p.name).join(', '))}</p><div class="actions">${button('load-encounter','Загрузить','secondary',e.id)}${button('delete-encounter','Удалить','quiet',e.id)}</div></article>`).join('') || '<p class="muted">Сохраните состав встречи, чтобы использовать его в следующей сессии.</p>'}</div></details><div class="note-strip">${icon('music')}<p>Музыка и звуки продолжают играть, пока вы ведёте бой.</p>${button('go-sound','Звуковая панель','text-button')}${button('new-event','Записать событие','text-button')}</div>`;
}
export function soundPage(c, mixer) {
  const s = c.soundboard;
  return `${sectionHead('АТМОСФЕРА ВАШЕЙ ИГРЫ', 'Музыка и звуки', 'Смешивайте музыку, фон и короткие эффекты. Всё хранится на устройстве.', button('new-sound',icon('plus') + ' Добавить аудио','primary'))}
  <div class="sound-master panel"><div><p class="eyebrow">ОБЩАЯ ГРОМКОСТЬ</p><label class="volume-line"><input type="range" min="0" max="100" value="${Math.round(s.masterVolume*100)}" data-volume="master" aria-label="Общая громкость"><output>${Math.round(s.masterVolume*100)}%</output></label></div><div class="actions">${button('save-mood','Сохранить звучащую сцену','secondary')}${button('stop-audio','■ Остановить всё','primary')}</div></div>
  <div class="sound-scenes"><div class="section-title"><h2>Звуковые сцены</h2><span class="muted tiny">Включить набор звуков одним нажатием</span></div><div class="mood-list">${s.moods.map(m => `<div class="mood-card">${button('play-mood', '▶ ' + esc(m.name), 'secondary', m.id)}<span class="muted tiny">${m.layers.length} слоёв</span>${button('delete-mood','×','icon-button',m.id)}</div>`).join('') || '<p class="muted tiny">Включите фон и музыку, настройте громкость и сохраните сцену — например, «Таверна».</p>'}</div></div>
  <div class="sound-columns">${Object.entries(SOUND_KINDS).map(([kind,label]) => `<section class="sound-section"><div class="section-title"><h2>${label}</h2><span class="count">${s.tracks.filter(t=>t.kind===kind).length}</span></div><div class="sound-grid">${s.tracks.filter(t=>t.kind===kind).map(t => `<article class="sound-card panel ${mixer.playing(t.id) ? 'playing' : ''}" data-track-card="${t.id}"><div class="sound-card-head"><span class="sound-glyph">${icon('music')}</span><span class="badge">${t.loop ? 'Повтор' : 'Один раз'}</span></div><h3>${esc(t.name)}</h3><p class="muted tiny">${esc(t.fileName)} · ${(t.bytes/1048576).toFixed(1)} МБ</p><label class="volume-line"><input type="range" min="0" max="100" value="${Math.round(mixer.level(t.id,t.volume)*100)}" data-volume="${t.id}" aria-label="Громкость: ${esc(t.name)}"><output>${Math.round(mixer.level(t.id,t.volume)*100)}%</output></label><div class="actions">${button('play-sound', kind === 'effect' ? '▶ Запустить эффект' : mixer.playing(t.id) ? 'Ⅱ Пауза' : '▶ Воспроизвести', 'primary', t.id)}${button('edit-sound','Настройки','quiet',t.id)}</div></article>`).join('') || `<div class="sound-empty">${kind === 'effect' ? 'Удары, шаги, гром или заклинания — запуск по нажатию.' : kind === 'ambience' ? 'Дождь, костёр, лес или шум таверны — вместе с музыкой.' : 'Добавьте музыку для путешествий, загадок и сражений.'}</div>`}</div></section>`).join('')}
  </div><p class="muted tiny">До 20 МБ на файл и 60 МБ аудио на кампанию. Файлы включаются в экспорт. После перезапуска звуки запускаются только по вашему нажатию.</p>`;
}
export function audioDock(c,mixer) {
  if (!c || !c.soundboard.tracks.length) return '';
  const playing = c.soundboard.tracks.filter(t=>mixer.playing(t.id));
  return `<div class="audio-dock"><div class="audio-dock-info">${icon('music')}<span><strong>${playing.length ? playing.map(t=>esc(t.name)).join(' + ') : 'Звуковая панель'}</strong><small>${playing.length ? playing.length + ' слоёв звучит' : 'Музыка и эффекты под рукой'}</small></span></div><div class="dock-effects">${c.soundboard.tracks.filter(t=>t.kind==='effect').slice(0,4).map(t=>button('play-sound',esc(t.name),'secondary',t.id)).join('')}</div>${button('go-sound','Открыть','quiet')}${button('stop-audio','■ Стоп','secondary')}</div>`;
}
