import { SOUND_KINDS } from './domain.js';
import { esc, icon, button, sectionHead, empty } from './ui.js';

export { combatPage } from './combat-ui.js';
export function soundPage(c, mixer) {
  const s = c.soundboard;
  return `${sectionHead('АТМОСФЕРА ВАШЕЙ ИГРЫ', 'Музыка и звуки', 'Смешивайте музыку, фон и короткие эффекты. Всё хранится на устройстве.', button('new-sound',icon('plus') + ' Добавить аудио','primary'))}
  <div class="sound-master panel"><div><p class="eyebrow">ОБЩАЯ ГРОМКОСТЬ</p><label class="volume-line"><input type="range" min="0" max="100" value="${Math.round(s.masterVolume*100)}" data-volume="master" aria-label="Общая громкость"><output>${Math.round(s.masterVolume*100)}%</output></label></div><div class="actions">${button('save-mood','Сохранить звучащую сцену','secondary')}${button('stop-audio','■ Остановить всё','primary')}</div></div>
  <div class="sound-scenes"><div class="section-title"><h2>Звуковые сцены</h2><span class="muted tiny">Включить набор звуков одним нажатием</span></div><div class="mood-list">${s.moods.map(m => `<div class="mood-card">${button('play-mood', '▶ ' + esc(m.name), 'secondary', m.id)}<span class="muted tiny">${m.layers.length} слоёв</span>${button('delete-mood','×','icon-button',m.id)}</div>`).join('') || '<p class="muted tiny">Включите фон и музыку, настройте громкость и сохраните сцену — например, «Таверна».</p>'}</div></div>
  <div class="sound-columns">${Object.entries(SOUND_KINDS).map(([kind,label]) => `<section class="sound-section"><div class="section-title"><h2>${label}</h2><span class="count">${s.tracks.filter(t=>t.kind===kind).length}</span></div><div class="sound-grid">${s.tracks.filter(t=>t.kind===kind).map(t => `<article class="sound-card panel ${mixer.playing(t.id) ? 'playing' : ''}" data-track-card="${t.id}"><div class="sound-card-head"><span class="sound-glyph">${icon('music')}</span><span class="badge">${t.loop ? 'Повтор' : 'Один раз'}</span></div><h3>${esc(t.name)}</h3><p class="muted tiny">${esc(t.fileName)} · ${(t.bytes/1048576).toFixed(1)} МБ</p><label class="volume-line"><input type="range" min="0" max="100" value="${Math.round(mixer.level(t.id,t.volume)*100)}" data-volume="${t.id}" aria-label="Громкость: ${esc(t.name)}"><output>${Math.round(mixer.level(t.id,t.volume)*100)}%</output></label><div class="actions">${button('play-sound', kind === 'effect' ? '▶ Запустить эффект' : mixer.playing(t.id) ? 'Ⅱ Пауза' : '▶ Воспроизвести', 'primary', t.id)}${button('edit-sound','Настройки','quiet',t.id)}</div></article>`).join('') || `<div class="sound-empty">${kind === 'effect' ? 'Удары, шаги, гром или заклинания — запуск по нажатию.' : kind === 'ambience' ? 'Дождь, костёр, лес или шум таверны — вместе с музыкой.' : 'Добавьте музыку для путешествий, загадок и сражений.'}</div>`}</div></section>`).join('')}
  </div><p class="muted tiny">До 20 МБ на файл и 60 МБ аудио на кампанию. Файлы включаются в экспорт. После перезапуска звуки запускаются только по вашему нажатию.</p>`;
}
export function audioDock(c,mixer) {
  if (!c || !c.soundboard.tracks.length) return '';
  const playing = c.soundboard.tracks.filter(t=>mixer.playing(t.id));
  return `<div class="audio-dock"><div class="audio-dock-info">${icon('music')}<span><strong>${playing.length ? playing.map(t=>esc(t.name)).join(' + ') : 'Звуковая панель'}</strong><small>${playing.length ? playing.length + ' слоёв звучит' : 'Музыка и эффекты под рукой'}</small></span></div><div class="dock-effects">${c.soundboard.tracks.filter(t=>t.kind==='effect').slice(0,4).map(t=>button('play-sound',esc(t.name),'secondary',t.id)).join('')}</div>${button('go-sound','Открыть','quiet')}${button('stop-audio','■ Стоп','secondary')}</div>`;
}
