import { cp, mkdir, readFile, writeFile, rename, rm, chmod } from 'node:fs/promises';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
const require=createRequire(import.meta.url),root=fileURLToPath(new URL('../',import.meta.url));
if(process.platform!=='linux'||process.arch!=='x64')throw new Error('Эта сборка пока проверена только для Linux x64.');
const version=JSON.parse(await readFile(join(root,'package.json'),'utf8')).version;
const target=join(root,'dist',`DM-Workbench-${version}-linux-x64`),appDir=join(target,'resources','app');
await rm(target,{recursive:true,force:true});await mkdir(target,{recursive:true});
await cp(dirname(require('electron')),target,{recursive:true});await mkdir(appDir,{recursive:true});
for(const path of ['app','assets','desktop','index.html','manifest.webmanifest','package.json','THIRD_PARTY.md','README.md','docs'])await cp(join(root,path),join(appDir,path),{recursive:true});
await mkdir(join(appDir,'scripts'));
for(const name of ['serve.mjs','local-assistant.mjs','memory-vault.mjs','ai-runtime.mjs','setup-local-ai.mjs','desktop-checks.mjs'])await cp(join(root,'scripts',name),join(appDir,'scripts',name));
await rename(join(target,'electron'),join(target,'dm-workbench'));await chmod(join(target,'dm-workbench'),0o755);
await writeFile(join(target,'start.sh'),'#!/bin/sh\napp_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)\nexec "$app_dir/dm-workbench" "$@"\n',{mode:0o755});
await writeFile(join(target,'README-RU.txt'),`DM Workbench ${version}\n\nЗапуск: ./start.sh\nДанные по умолчанию: папка «DM Workbench» в Документах.\nДругую папку можно выбрать в разделе «Хранилище».\nДля ИИ используйте установленный Ollama или кнопку загрузки в приложении.\nМодель ИИ в эту сборку не включена. Интернет после её загрузки не нужен.\nДля переноса старых кампаний импортируйте JSON из веб-версии, затем профиль стиля и папку памяти.\n\nСборка для Linux x64. Windows/macOS пока не проверены.\n`);
const archive=target+'.tar.gz';
await new Promise((resolve,reject)=>{const p=spawn('tar',['-czf',archive,'-C',dirname(target),target.split('/').at(-1)],{stdio:'inherit'});p.on('error',reject);p.on('exit',code=>code===0?resolve():reject(new Error('Не удалось создать архив.')));});
console.log(target);console.log(archive);
